using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class CommercialSaleDetail
{
    public int CommercialSaleDetailsId { get; set; }

    public decimal? Price { get; set; }

    public virtual ICollection<CommercialOfferDetail> CommercialOfferDetails { get; set; } = new List<CommercialOfferDetail>();
}
