using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class CommercialLeasingPermission
{
    public byte CommercialLeasingPermissionId { get; set; }

    public string? Name { get; set; }
}
