using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class CommercialContractType
{
    public byte CommercialContractTypeId { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<CommercialOfferDetail> CommercialOfferDetails { get; set; } = new List<CommercialOfferDetail>();
}
