using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class CommercialOfferDetail
{
    public int CommercialOfferDetailsId { get; set; }

    public byte FkCommercialContractTypeId { get; set; }

    public int? FkCommercialLeasingDetailsId { get; set; }

    public int? FkCommercialSaleDetailsId { get; set; }

    public byte FkCommercialEstateTypeId { get; set; }

    public int? FkShopDetailsId { get; set; }

    public int? FkWarehouseDetailsId { get; set; }

    public int? FkOfficeDetailsId { get; set; }

    public int? FkRestaurantDetailsId { get; set; }

    public virtual CommercialContractType FkCommercialContractType { get; set; } = null!;

    public virtual CommercialEstateType FkCommercialEstateType { get; set; } = null!;

    public virtual CommercialLeasingDetail? FkCommercialLeasingDetails { get; set; }

    public virtual CommercialSaleDetail? FkCommercialSaleDetails { get; set; }

    public virtual OfficeDetail? FkOfficeDetails { get; set; }

    public virtual RestaurantDetail? FkRestaurantDetails { get; set; }

    public virtual ShopDetail? FkShopDetails { get; set; }

    public virtual WarehouseDetail? FkWarehouseDetails { get; set; }

    public virtual ICollection<Offer> Offers { get; set; } = new List<Offer>();
}
