using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class CommercialLeasingDetail
{
    public int CommercialLeasingDetailsId { get; set; }

    public decimal? PricePerDay { get; set; }

    public decimal? PricePerMonth { get; set; }

    public decimal? PricePerYear { get; set; }

    public virtual ICollection<CommercialOfferDetail> CommercialOfferDetails { get; set; } = new List<CommercialOfferDetail>();
}
