using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class CommercialEstateType
{
    public byte CommercialEstateTypeId { get; set; }

    public string? Name { get; set; }

    public virtual ICollection<CommercialOfferDetail> CommercialOfferDetails { get; set; } = new List<CommercialOfferDetail>();
}
