using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class FlatDetail
{
    public int FlatDetailsId { get; set; }

    public float? Square { get; set; }

    public short? FloorNumber { get; set; }

    public short? RoomNumber { get; set; }

    public short? Wcnumber { get; set; }

    public virtual ICollection<ResidentialOfferDetail> ResidentialOfferDetails { get; set; } = new List<ResidentialOfferDetail>();
}
