using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class HouseDetail
{
    public int HouseDetailsId { get; set; }

    public float? Square { get; set; }

    public short? FloorNumber { get; set; }

    public string? FlatNumber { get; set; }

    public bool? SwimmingPoolAvailable { get; set; }

    public bool? GarageAvailable { get; set; }

    public virtual ICollection<ResidentialOfferDetail> ResidentialOfferDetails { get; set; } = new List<ResidentialOfferDetail>();
}
