using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class M2mCommercialPermissionsLeasingDetail
{
    public int FkCommercialLeaingDetailsId { get; set; }

    public byte? FkCommercialLeasingPermissionId { get; set; }

    public virtual CommercialLeasingDetail FkCommercialLeaingDetails { get; set; } = null!;

    public virtual CommercialLeasingPermission? FkCommercialLeasingPermission { get; set; }
}
