using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class M2mResidentialPermissionsLeaseDetail
{
    public int FkResidentialLeaseDetailsId { get; set; }

    public byte FkResidentialLeasePermissonId { get; set; }

    public virtual ResidentialLeaseDetail FkResidentialLeaseDetails { get; set; } = null!;

    public virtual ResidentialLeasePermission FkResidentialLeasePermisson { get; set; } = null!;
}
