using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class Offer
{
    public int OfferId { get; set; }

    public int FkUserId { get; set; }

    public byte? FkOfferTypeId { get; set; }

    public int? FkCommercialOfferDetailsId { get; set; }

    public int? FkResidentialOfferDetailsId { get; set; }

    public DateTime? PublicationDate { get; set; }

    public string? Description { get; set; }

    public string? Address { get; set; }

    public virtual CommercialOfferDetail? FkCommercialOfferDetails { get; set; }

    public virtual OfferType? FkOfferType { get; set; }

    public virtual ResidentialOfferDetail? FkResidentialOfferDetails { get; set; }

    public virtual User FkUser { get; set; } = null!;
}
