using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class OfferType
{
    public byte OfferTypeId { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<Offer> Offers { get; set; } = new List<Offer>();
}
