using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class OfficeDetail
{
    public int OfficeDetailsId { get; set; }

    public float? Square { get; set; }

    public float? ConstTemperature { get; set; }

    public virtual ICollection<CommercialOfferDetail> CommercialOfferDetails { get; set; } = new List<CommercialOfferDetail>();
}
