using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class ResidentialSaleDetail
{
    public int ResidentialSaleDetailsId { get; set; }

    public decimal? Price { get; set; }

    public virtual ICollection<ResidentialOfferDetail> ResidentialOfferDetails { get; set; } = new List<ResidentialOfferDetail>();
}
