using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class ResidentialContractType
{
    public byte ResidentialContractTypeId { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<ResidentialOfferDetail> ResidentialOfferDetails { get; set; } = new List<ResidentialOfferDetail>();
}
