using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class ResidentialLeaseDetail
{
    public int ResidentialLeaseDetailsId { get; set; }

    public decimal? PricePerYear { get; set; }

    public decimal? PricePerMonth { get; set; }

    public decimal? PricePerDay { get; set; }

    public virtual ICollection<ResidentialOfferDetail> ResidentialOfferDetails { get; set; } = new List<ResidentialOfferDetail>();
}
