using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class RestaurantDetail
{
    public int RestaurantDetailsId { get; set; }

    public float? Square { get; set; }

    public short? MaxGuestNumber { get; set; }

    public virtual ICollection<CommercialOfferDetail> CommercialOfferDetails { get; set; } = new List<CommercialOfferDetail>();
}
