using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class ShopDetail
{
    public int ShopDetailsId { get; set; }

    public float? Square { get; set; }

    public short? FloorNumber { get; set; }

    public short? Wcnumber { get; set; }

    public virtual ICollection<CommercialOfferDetail> CommercialOfferDetails { get; set; } = new List<CommercialOfferDetail>();
}
