using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class UserContact
{
    public int FkUserId { get; set; }

    public byte UserContactId { get; set; }

    public string Contact { get; set; } = null!;

    public virtual User FkUser { get; set; } = null!;
}
