using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class User
{
    public int UserId { get; set; }

    public string Name { get; set; } = null!;

    public byte FkUserTypeId { get; set; }

    public int? FkAgencyDetailsId { get; set; }

    public string? RegLogin { get; set; }

    public string? RegPassword { get; set; }

    public bool Status { get; set; }

    public virtual AgencyDetail? FkAgencyDetails { get; set; }

    public virtual UserType FkUserType { get; set; } = null!;

    public virtual ICollection<Offer> Offers { get; set; } = new List<Offer>();

    public virtual ICollection<UserContact> UserContacts { get; set; } = new List<UserContact>();
}
