using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class UserType
{
    public byte UserTypeId { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}
