using System;
using System.Collections.Generic;

namespace Backend.Entities.Autogenerated;

public partial class WarehouseDetail
{
    public int WarehouseDetailsId { get; set; }

    public float? Square { get; set; }

    public float? CeilingHeight { get; set; }

    public virtual ICollection<CommercialOfferDetail> CommercialOfferDetails { get; set; } = new List<CommercialOfferDetail>();
}
